### ISSUE TITLE
bug:  Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found when implement cronJobs

### ISSUE THREAD

**Issue by indratrisnar** [invertase/globe#200]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### CLI Version

not using CLI

### Project ID

d819057b-d58a-4526-bd17-e5cb3db32cd4

### Description

I want to implement CronJobs on my dart_frog project, and i follow this instruction: https://docs.globe.dev/core-concepts/cron-jobs
when i deploy to globe via github, i always get this error:

![Image](https://github.com/user-attachments/assets/a1c3a022-35d5-496c-9bd9-931202538bdc)

after i research for many possibility, i can confirm this error always show after i deploy 'globe.yaml'.

here my globle.yaml

```yaml
crons:
  - id: reset_note_id_daily
    schedule: "*/5 * * * *"
    path: "/cron/reset-note-id"
    private: true
    headers:
      Cron-Secret-Key: ${CRON_SECRET_KEY} # Globe.dev will inject the value of the CRON_SECRET_KEY
```

if i remove globe.yaml. it work fine. but i cannot do cron Jobs

### Steps to reproduce

Implement cronJobs.

1. create endpoint
2. setup globe.yaml
3. deploy via github

### Expected behavior

got error when verifying deployment.

![Image](https://github.com/user-attachments/assets/a1c3a022-35d5-496c-9bd9-931202538bdc)
